#!/bin/bash -e

apt-get -y --no-upgrade install \
    python3 \
    python3-invoke \
    psutils \
    python3-psycopg2 \
    python3-psutil \
    postgresql-9.4 \
    python3-postgresql \
    python3-django \
    python3-django-tastypie \
    python3-yaml \
    python3-mimeparse \
    python3-dateutil \
    python3-requests \
    apache2 \
    python \
    python-selenium \
    python3-flake8 \
    libapache2-mod-wsgi-py3 \
    pandoc \
    python3-pytest \
    python3-freezegun \
    python3-pip \
    python3-arrow \
    libjs-yui3-min \
    libjs-angularjs \
    libjs-yui \
    python3-pyparsing \
    python3-pydot \
    --fix-missing

# export https_proxy=http://91.189.89.33:3128
pip3 install django-tastypie-swagger
pip3 install django-extensions
