#!/bin/bash -e

apt-get -y --no-upgrade install \
    python3 \
    python3-invoke \
    psutils \
    python3-psycopg2 \
    python3-psutil \
    postgresql-9.4 \
    python3-postgresql \
    python3-django \
    python3-django-tastypie \
    python3-yaml \
    python3-mimeparse \
    python3-dateutil \
    python3-requests \
    apache2 \
    python \
    python-selenium \
    python3-flake8 \
    libapache2-mod-wsgi-py3 \
    pandoc \
    python3-pytest \
    python3-freezegun \
    python3-pip \
    python3-arrow \
    libjs-yui3-min \
    libjs-angularjs \
    libjs-yui \
    npm \
    python3-pyparsing \
    python3-pydot \
    --fix-missing

# Wily has a weird mix of python3.4 and python3.5. pip3 installs dependencies
# under python3.5 so we need to make python3 use python3.5.
ubuntu_release=$(lsb_release -c -s)
if [[ $ubuntu_release == 'wily' ]]
then
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 10
fi

# export https_proxy=http://91.189.89.33:3128

echo "Installing packages via pip3"
pip3 install django-tastypie-swagger django-extensions

echo "(Run 'invoke install_npm_pkgs' to install packages via npm)"

echo "Done"
# unset https_proxy
