#!/bin/bash

ARSENAL_SCRIPTS="../../scripts"
ARSENAL_TEMPLATES="../../web/templates"

set -e

for jfid in hwe-*.json; do
    title=${jfid%%.json}
    title=${title##hwe-}
    title=${title^}
    echo $title
    ${ARSENAL_SCRIPTS}/collect-project-bug-data --privates $jfid
    ${ARSENAL_SCRIPTS}/reporter \
	--title=$title \
	--template=${ARSENAL_TEMPLATES}/bugs-by-hwe-project.mako \
	$jfid > ${jfid/.json/.html}
done
