#!/usr/bin/perl

# Given an upstream bugzilla url, extract info, patches, git commit ids, etc.

use strict;
use Pod::Usage;
use Getopt::Long qw(:config no_ignore_case bundling);
use LWP::Simple;
use JSON;

our $opt_help         = 0;
our $opt_data         = 0;
our $opt_version      = 0;
our $opt_json         = 0;

Getopt::Long::Configure ("bundling", "no_ignore_case");
GetOptions(
           "version|v",
           "help|h",
           "data|d",
           "json|j",
           ) or pod2usage(-verbose => 0, -exitstatus => 0);

if (@ARGV < 1) {
    print "Error:  Insufficient arguments\n";
    pod2usage(-verbose => 0, -exitstatus => 1);
}

version_and_exit() if $opt_version;

sub version_and_exit
{
    print "Copyright (C) 2009 Bryce W. Harrington <bryce\@bryceharrington.org>\n";
    print "This program is free software; you can redistribute it and/or\n";
    print "modify it under the same terms as Perl itself.\n";
    exit(0);
}


my $url = shift @ARGV;
my $content = get($url);

my %Bug;
foreach my $line ( split(/\<tr/, $content) ) {
    if ($line =~ m|<td id="title">|) {
        if ($line =~ m|<p>(Bugzilla &ndash; Bug.*)</p>|) {
            $Bug{'title'} = $1;
        }
        if ($line =~ m|<p class="subheader">(.*?)</p>|) {
            $Bug{'subtitle'} = $1;
        }
        if ($line =~ m|<p class="header_addl_info">Last modified: (.*?)</p>|) {
            $Bug{'last_modified'} = $1;
        }
    }

    if ($line =~ m|<label for="product"|) {
        if ($line =~ m|<option value="(.*?)" selected>|) {
            $Bug{'product'} = $1;
        }
    }

    if ($line =~ m|<label for="component"|) {
        if ($line =~ m|<option value="(.*?)" selected>|) {
            $Bug{'component'} = $1;
        }
    }

    if ($line =~ m|<b><a href="page.cgi\?id=fields.html#status">Status</a></b>|) {
        if ($line =~ m|<td>(.*?)</td>|) {
            $Bug{'status'} = $1;
        }
    }

    if ($line =~ m|<b><a href="page.cgi\?id=fields.html#resolution">Resolution</a></b>|) {
        if ($line =~ m|<td>(.*?)</td>|) {
            $Bug{'resolution'} = $1;
        }
    }

    if ($line =~ m|<label for="rep_platform"|) {
        if ($line =~ m|<option value="(.*?)" selected>|) {
            $Bug{'platform'} = $1;
        }
    }

    if ($line =~ m|<label for="op_sys"|) {
        if ($line =~ m|<option value="(.*?)" selected>|) {
            $Bug{'operating_system'} = $1;
        }
    }

    if ($line =~ m|<label for="version"|) {
        if ($line =~ m|<option value="(.*?)" selected>|) {
            $Bug{'version'} = $1;
        }
    }

    if ($line =~ m|<label for="priority"|) {
        if ($line =~ m|<option value="(.*?)" selected>|) {
            $Bug{'priority'} = $1;
        }
    }

    if ($line =~ m|<label for="bug_severity"|) {
        if ($line =~ m|<option value="(.*?)" selected>|) {
            $Bug{'severity'} = $1;
        }
    }

    if ($line =~ m|<b>Reporter</b>:|) {
        if ($line =~ m|<a href="mailto:(.*)">(.*) &lt;|) {
            $Bug{'reporter_email'} = $1;
            $Bug{'reporter_name'} = $2;
        }
    }

    if ($line =~ m|Assigned&nbsp;To</a></b>:|) {
        if ($line =~ m|<a href="mailto:(.*)">(.*) &lt;|) {
            $Bug{'assignee_email'} = $1;
            $Bug{'assignee_name'} = $2;
        }
    }

    if ($line =~ m|<u>Q</u>A Contact</b></label>:|) {
        if ($line =~ m|<a href="mailto:(.*)">(.*) &lt;|) {
            $Bug{'qa_contact_email'} = $1;
            $Bug{'qa_contact_name'} = $2;
        }
    }

    if ($line =~ m|<label for="cc">|) {
        my @contacts = ();
        if ($line =~ m|<option value="(.*)">(.*)</option>|) {
            push @contacts, {'email'=>$1, 'name'=>$2};
        }
        $Bug{'contacts'} = \@contacts;
    }

    # Attachments
    if ($line =~ m|title="View the content of the attachment">|) {
        my %attachment;
        if ($line =~ m|href="attachment.cgi\?id=(\d+)"|) {
            $attachment{'id'} =  $1;
        }
        if ($line =~ m|<b>(.*)</b></a>|) {
            $attachment{'title'} = $1;
        }
        if ($line =~ m|patch\)|) {
            $attachment{'is_patch'} = 1;
        }
        if ($line =~ m|title="Write an email to the creator of the attachment">(.*)|) {
            $attachment{'creator'} = $1;
        }
        push @{$Bug{'attachments'}}, \%attachment;
    }
}

if ($opt_json) {
    print to_json(\%Bug, {pretty=>1}), "\n";
} else {
    printf("%-40s %s\n", $Bug{'subtitle'}, $Bug{'last_modified'});
}
