#!/usr/bin/python

# List bugs that have been linked to a given blueprint

import sys
import simplejson as json
import datetime
import socket
from optparse import OptionParser
from lpltk import LaunchpadService

usage = '''
%prog [options] <blueprint> [blueprint ...]
'''
parser = OptionParser(usage=usage)
parser.add_option(
    '-d', '--debug',
    action='store_true', dest='DEBUG', default=False,
    help='Enable debugging output')
(options, args) = parser.parse_args()

if len(args) < 1:
    parser.print_help()
    sys.exit(1)

try:
    blueprints  = args
    lp          = LaunchpadService(config={'read_only':True})
    d           = lp.distributions['ubuntu']
    records     = []
except:
    raise
    sys.exit(7)

for blueprint_name in blueprints:
    try:
        bp = d.get_specification(blueprint_name)
        if not bp:
            sys.stderr.write("Error:  Could not get blueprint '%s'\n" %(blueprint_name))
            sys.exit(1)
        for bug in bp.bugs:
            bug_dict = bug.to_dict()
            for bugtask in bug.tasks:
                record = bugtask.to_dict()
                record.update(bug_dict)
                records.append(record)

    except socket.error as e:
        # Network is down.  Skip for now
        sys.exit(7)

    except:
        sys.stderr.write("Unknown exception encountered\n")
        # TODO:  ValueError
        raise

keys = ['id', 'title', 'status', 'importance', 'target', 'assignee', 'releases']
print json.dumps({
    'keys':keys,
    'bug_tasks':records,
    'timestamp-stop':str(datetime.datetime.now())
    }, indent=4)
