#!/usr/bin/python

import sys, os, re
from lpltk import LaunchpadService

# TODO: Cache the series?

try:
    lp          = LaunchpadService(config={'read_only':True})
    d           = lp.launchpad.distributions["ubuntu"]
    n           = d.current_series.name
    regex       = re.compile(r'The authorization page')
    if regex.match(n):
        sys.exit(1)
    print n

except:
    sys.exit(7)

sys.exit(0)
