#!/usr/bin/perl

use Template;
use JSON;

my $tt2file  = '/home/bryce/src/Gantry/table.tt2';
my @columns =
    (
     { title => '',           field => 'flags' },
     { title => '',           field => 'id',               format => 'integer', },
     { title => 'Report',     field => 'title',
       link_url => "http://bugs.launchpad.net/bugs/",      link_field => "id" },
     { title => 'Importance', field => 'importance', },
     { title => 'Status',     field => 'status' },
     { title => 'Source',     field => 'source' },
     { title => 'Assignee',   field => 'assignee',
       link_url => "http://launchpad.net/~",               link_field => "assignee" },
     { title => 'Milestone',  field => 'milestone',
       link_url => "https://launchpad.net/ubuntu/+milestone/", link_field => "milestone" },
     { title => 'Dupes',      field => 'dupes',            format => 'integer',
       yellow => 5, orange => 10, red => 20, },
     { title => 'Age',        field => 'age',              format => 'integer',
       yellow => 5, orange => 10, red => 20, },
     { title => 'Last',       field => 'last_comment_age', format => 'integer',
       yellow => 5, orange => 10, red => 20, },
     { title => 'Subs',       field => 'num_subscribers',  format => 'integer',
       yellow => 5, orange => 10, red => 20, },
     { title => 'Cmts',       field => 'num_comments',     format => 'integer',
       yellow => 25, orange => 50, red => 100, },
     );

my $datafile = $ARGV[0] ||
    errmsg("Usage:  $0 <data-file.json>\n");

my $js = loadfile($datafile) ||
    errmsg("Error:  Content $datafile could not be loaded\n");

my $tt_config = {
    ABSOLUTE => 1,
};

my $json = jsonToObj( $js );
my $template = Template->new($tt_config);
my $vars = {
    bugs => $json,
    columns => \@columns,
};

$template->process($tt2file, $vars)
    || die $template->error();


sub errmsg {
    print @_;
    exit;
}

sub loadfile {
    local $/ = <> if local @ARGV = @_;
}

