#!/bin/bash

. $(dirname $0)/../lib/arsenal.lib

tag=`basename $0`
tag=${tag#data-}

file=${tag}.json

for team in `${ARSENAL_SCRIPTS}/desktop-teams`; do
    packages=`${ARSENAL_SCRIPTS}/ls-team-subscribed-packages.py -t ${team} | grep -v openchrome`
    if [ ! -z "${packages}" ] ; then
        capture "${ARSENAL_SCRIPTS}/collect-patch-bugs ${packages}" "${team}/Data" ${file}
    fi
done

