#!/bin/bash

. $(dirname $0)/../lib/arsenal.lib

tag=`basename $0`
blueprint=${tag#data-blueprint-bugs-}

file="blueprint-${blueprint}.json"
team="ubuntu-x-swat"

capture "${ARSENAL_SCRIPTS}/collect-blueprint-bugs ${blueprint}" "${team}/Data" ${file}
