#!/bin/bash

. $(dirname $0)/../lib/arsenal.lib

file=upstream-open-ati.json
team='ubuntu-x-swat'
packages='xserver-xorg-video-ati'

capture "${ARSENAL_SCRIPTS}/collect-upstream-bugs open ${packages}" "${team}/Data" ${file}

