#!/bin/bash

. $(dirname $0)/../lib/arsenal.lib

json_filename=bugtotals-${TODAY}.json

for project in inkscape; do
    capture "${ARSENAL_SCRIPTS}/collect-project-bugtotals ${project}" "${project}/Data/BugStats" ${json_filename}
done

