#!/bin/bash

. $(dirname $0)/../lib/arsenal.lib

tag=`basename $0`

devel=$(current-ubuntu-development-codename)
releases=$(current-ubuntu-supported-releases)

for team in $(${ARSENAL_SCRIPTS}/desktop-teams); do
    packages=$(${ARSENAL_SCRIPTS}/ls-team-subscribed-packages.py -t ${team})

    if [ ! -z "${packages}" ] ; then
        for codename in $devel $releases ; do
            file=workqueue-${codename}.json
            capture "${ARSENAL_SCRIPTS}/collect-workqueue-bugs.py ${codename} ${packages}" "${team}/Data" $file
        done
    fi

done

