#!/bin/bash

. $(dirname $0)/../lib/arsenal.lib

json_filename=bugtotals-${TODAY}.json

for team in `${ARSENAL_SCRIPTS}/desktop-teams`; do
    packages=$(${ARSENAL_SCRIPTS}/ls-team-subscribed-packages.py -t ${team} | grep -v linux-restricted-modules)
    if [ ! -z "${packages}" ] ; then
        capture "${ARSENAL_SCRIPTS}/collect-team-bugtotals ${packages}" "${team}/Data/BugStats" ${json_filename}
    fi
done

