#!/bin/bash

. $(dirname $0)/../lib/arsenal.lib

tag=`basename $0`
tag=${tag#page-}

html_filename=${tag}.html
json_filename=${tag}.json

BASE_DIR=/var/www/Arsenal

if [ ! -f $json ]; then
    exit 1
fi

for team in `${ARSENAL_SCRIPTS}/desktop-teams`; do
    if [ -f "${BASE_DIR}/${team}/Data/${json_filename}" ]; then
        capture "${ARSENAL_SCRIPTS}/bug-listing.py --show-assignee --show-last-message-age --title=${team}&nbsp;Bugs&nbsp;Open&nbsp;Upstream --show-source ${BASE_DIR}/${team}/Data/${json_filename}" "$team/Reports" ${html_filename}
    fi
done

