#!/bin/bash

. $(dirname $0)/../lib/arsenal.lib

html_filename=package_status_${TODAY}.html
#json_filename=package_status_${TODAY}.json
CHROOT=/srv/Chroot/xorg-pkg-list

#json=${DATA_DIR}/ubuntu-x-swat/Data/PackageStatus/${json_filename}
#
#if [ ! -f $json ]; then
#    exit 1
#fi

# Install collection script to chroot
# TODO: Rename this script to collect-package-status and generalize it
if [ -e ${ARSENAL_SCRIPTS}/collect-xorg-package-status ]; then
    cp ${ARSENAL_SCRIPTS}/collect-xorg-package-status $CHROOT/usr/local/bin
fi

/usr/sbin/chroot ${CHROOT} apt-get -qqq update 2>&1 | grep -v NO_PUBKEY

capture "/usr/sbin/chroot $CHROOT /usr/local/bin/collect-xorg-package-status --html" "ubuntu-x-swat/Reports/PackageStatus" ${html_filename}

relink_current "PackageStatus/${html_filename}" "ubuntu-x-swat/Reports" "package_status.html"
