#!/bin/bash

. $(dirname $0)/../lib/arsenal.lib

tag=`basename $0`
tag=${tag#page-}

html_filename=${tag}.html
json_filename=${tag}.json

BASE_DIR=/var/www/X

if [ ! -f $json ]; then
    exit 1
fi

for team in `${ARSENAL_SCRIPTS}/desktop-teams`; do
    if [ $team = 'openoffice-pkgs' ] ; then
        # Skip for now due to unicode issues
        continue
    fi
    if [ -f "${BASE_DIR}/${team}/Data/${json_filename}" ]; then
        capture "${ARSENAL_SCRIPTS}/bug-listing.py --show-assignee --show-milestone --show-last-message-age --title=${team}&nbsp;Milestone&nbsp;bugs --show-source ${BASE_DIR}/${team}/Data/${json_filename}" "$team/Reports" ${html_filename}
    fi
done

#capture "${ARSENAL_SCRIPTS}/bug-listing.py $json" "Milestones" ${html_filename}
#relink_current ${html_filename} "Milestones" "milestones_current.html"
