#!/bin/bash

. $(dirname $0)/../lib/arsenal.lib

BASE_DIR=/var/www/Arsenal

tag=`basename $0`
tag=${tag#page-}

devel=$(current-ubuntu-development-codename)
release=$(current-ubuntu-release-codename)

for team in `${ARSENAL_SCRIPTS}/desktop-teams`; do
    codename=${devel}
    json_filename=${tag}-${codename}.json
    html_filename=${tag}-${codename}.html
    if [ -f "${BASE_DIR}/${team}/Data/${json_filename}" ]; then
        capture "${ARSENAL_SCRIPTS}/bug-listing.py --title=${team}&nbsp;bugs&nbsp;tagged&nbsp;${codename}&nbsp;needing&nbsp;action --show-last-message-age --show-tags --show-assignee --show-source ${BASE_DIR}/${team}/Data/${json_filename}" "$team/Reports" ${html_filename}
    fi

    codename=${release}
    json_filename=${tag}-${codename}.json
    html_filename=${tag}-${codename}.html
    if [ -f "${BASE_DIR}/${team}/Data/${json_filename}" ]; then
        capture "${ARSENAL_SCRIPTS}/bug-listing.py --title=${team}&nbsp;bugs&nbsp;tagged&nbsp;${codename}&nbsp;needing&nbsp;action --show-last-message-age --show-tags --show-assignee --show-source ${BASE_DIR}/${team}/Data/${json_filename}" "$team/Reports" ${html_filename}
    fi
done


