#!/bin/bash

. $(dirname $0)/../lib/arsenal.lib

BASE_DIR=/var/www/Arsenal

tag=`basename $0`
tag=${tag#page-}

json_filename=${tag}.json
html_filename=${tag}.html

for team in `${ARSENAL_SCRIPTS}/desktop-teams`; do
    if [ -f "${BASE_DIR}/${team}/Data/${json_filename}" ]; then
        capture "${ARSENAL_SCRIPTS}/bug-listing.py --title=${team}&nbsp;bugs&nbsp;with&nbsp;patches --show-assignee --show-patches --show-source ${BASE_DIR}/${team}/Data/${json_filename}" "$team/Reports" ${html_filename}
    fi
done


