#!/bin/bash

. $(dirname $0)/../lib/arsenal.lib

scriptname=$(basename $0)
pagename=${scriptname#page-}

html_filename=${pagename}_${TODAY}.html
json_filename=${pagename}_${TODAY}.json

json=${WEBSITE_DIR}/${pagename}/Data/${json_filename}

if [ ! -f $json ]; then
    exit 1
fi

capture "${ARSENAL_SCRIPTS}/xorg_pkg_list $json" ${pagename} ${html_filename}

relink_current ${html_filename} ${pagename} "${pagename}_current.html"
